export const CATEGORIES = [
  "streetwear",
  "collectibles",
  "sneakers",
  "accesories",
  "watches",
];

export const BRANDS = [
  "Fear of God",
  "Pop Mart",
  "Jordan",
  "Nike",
  "ASICS",
  "UGG",
  "Timberland",
  "adidas",
  "New Balance",
  "Maison Mihara Yasuhiro",
  "The North Face",
  "Sony",
  "Crocs",
  "Birkenstock",
  "Arc'teryx",
  "Rigorer",
  "Converse",
  "Sp5der",
  "Supreme",
  "LEGO",
  "Travis Scott",
  "Denim Tears",
  "Vans",
  "Yeezy",
  "BAPE",
  "Prada",
  "Sprayground",
  "Bratz",
  "Palace",
  "Burberry",
  "Louis Vuitton",
  "Anta",
  "Puma",
  "Maison Margiela",
  "Anti Social Social Club",
  "Salomon",
  "361 Degrees",
  "AMD",
  "Casio",
  "Gucci",
  "On",
  "Dior",
  "Balenciaga",
  "Topps",
  "OFF-WHITE",
  "Reebok",
  "Hoka One One",
  "Swatch",
  "Revenge",
  "Pokemon",
  "Alexander McQueen",
  "Stussy",
  "AMIRI",
  "Panini",
  "Bearbrick",
  "KAWS",
  "Timex",
  "Tesla",
  "Versace",
  "SKIMS",
  "Finalmouse",
  "Polo Ralph Lauren",
  "Saucony",
  "Kith",
  "Kanye West",
  "Telfar",
];

export const CATEGORY_BRANDS = [
  {
    category: "streetwear",
    brands: [
      "Fear of God",
      "Nike",
      "The North Face",
      "Arc'teryx",
      "Sp5der",
      "Supreme",
      "Travis Scott",
      "Denim Tears",
      "Yeezy",
      "BAPE",
      "Sprayground",
      "Palace",
      "Jordan",
      "Burberry",
      "Anti Social Social Club",
      "OFF-WHITE",
      "Revenge",
      "Stussy",
      "adidas",
      "KAWS",
      "AMIRI",
      "SKIMS",
      "Polo Ralph Lauren",
      "Kith",
      "Kanye West",
      "Louis Vuitton",
    ],
  },
  {
    category: "collectibles",
    brands: [
      "Pop Mart",
      "Sony",
      "LEGO",
      "Bratz",
      "AMD",
      "Topps",
      "Pokemon",
      "Panini",
      "Bearbrick",
      "Tesla",
      "Finalmouse",
    ],
  },
  {
    category: "sneakers",
    brands: [
      "Jordan",
      "Nike",
      "ASICS",
      "UGG",
      "Timberland",
      "adidas",
      "New Balance",
      "Maison Mihara Yasuhiro",
      "Crocs",
      "Birkenstock",
      "Rigorer",
      "Converse",
      "Vans",
      "Anta",
      "Puma",
      "Maison Margiela",
      "Salomon",
      "361 Degrees",
      "Yeezy",
      "Gucci",
      "On",
      "Dior",
      "Balenciaga",
      "OFF-WHITE",
      "Burberry",
      "Reebok",
      "Hoka One One",
      "Alexander McQueen",
      "AMIRI",
      "BAPE",
      "Saucony",
    ],
  },
  {
    category: "accesories",
    brands: [
      "Prada",
      "Louis Vuitton",
      "Gucci",
      "Burberry",
      "Versace",
      "Balenciaga",
      "Telfar",
    ],
  },
  { category: "watches", brands: ["Casio", "Swatch", "Timex"] },
];
